# Useful commands

# Development Workflow
# $ cargo make

# Watches for any file change and if any change is detected, it will invoke the default flow.
# $ cargo make watch-flow

# Full sanity testing flow
# $ cargo make build-flow

# Publish
# Note: Remember to increment the crate version beforehand
# $ env COMMIT_MSG="Put your commit MESSAGE here"  cargo make build-publish-flow

# Run git add .
# $ cargo make git-add

[env]
#This is required because on our development machines we mirror crates-io to speed up builds, and allow offline development
CARGO_MAKE_CARGO_PUBLISH_FLAGS="--registry crates-io"

#CARGO_MAKE_GIT_PUSH_ARGS
GITHUB_API_TOKEN="xxx"
GITHUB_REPO_NAME="xxx"
CARGO_MAKE_GIT_BRANCH="main"

[tasks.generate-readme]
command = "cargo"
args = [ "readme","-o","README.md" ]

[tasks.pre-git-add]
dependencies = ["generate-readme"]

# TODO figure out why preconditions on default build-publish-flow are not met
[tasks.build-publish-flow]
dependencies = [
    "delete-lock",
    "build-flow",
    "build-file-increment-flow",
    "git-add",
    "git-status",
    "git-commit-message",
    "git-push",
    "git-delete-merged-branches",
    "github-publish-custom-name",
    "publish-flow",
    "upload-artifacts",
    "git-pull",
]

